#!/usr/bin/env bash

[[ -v SNAP_PAC_SKIP ]] && { printf "==> skipping due to SNAP_PAC_SKIP being set"; exit 0; }

echo "Running grub-mkconfig..."
grub-mkconfig -o /boot/grub/grub.cfg >~/grub_error 2>&1
STATUS=$?
if [ $STATUS -eq 0 ]; then
    echo "Succes"
else
    echo "FAILED! Err code: $STATUS"
fi
